### ISSUE TITLE
GitHub action automation

### ISSUE THREAD

**Issue by yegor256** [potatmen/Life#1]
Let's add GitHub Action automation, which must build the product and run all its tests.

**Comment by potatmen** [comment]
@yegor256 Added. All pushes are checked by installing boost library and running `$ make`. In addition to this, unit tests will be added and run.

**Comment by yegor256** [comment]
@potatmen cool thanks

**Comment by potatmen** [comment]
@yegor256 Tests running added to Actions, more tests will be added  https://github.com/potatmen/Life/commit/8cca98213c690ff50e2b886da091c30f9c8c509c
