### ISSUE TITLE
--sleep

### ISSUE THREAD

**Issue by yegor256** [potatmen/Life#10]
Let's add `--sleep` command line option, which will cause a delay between life cycles, in milliseconds:

```
$ ./life --sleep 500 --cycles=100
```

This should lead to delays of 0.5s between cycles.

**Comment by potatmen** [comment]
@yegor256 Done

**Comment by yegor256** [comment]
@potatmen where?) read this: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/autolinked-references-and-urls#issues-and-pull-requests

**Comment by yegor256** [comment]
@potatmen thanks!
